# .github/workflows/main.yml
name: CI Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  ci_pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: InfraConfig
        env: 
          MY_API_KEY: ${{ secrets.CUSTOM_API_KEY }}
        uses: ./actions # Usa la action creada en este repositorio.
        with:
          command: "apt update -y"
          secrets: "echo ${{ MY_API_KEY }}"

      - name: Build
        run: echo "Building"

      - name: Deploy
        run: echo "Deploying"

      - name: Test
        run: echo "Test"
